### ISSUE TITLE
[vivado_synth.tcl] Property generic set incorrectly, if rtl.parameters has multiple items

### ISSUE THREAD

**Issue by rennx0101** [XedaHQ/xeda#40]
In the jinja template "vivado_synth.tcl", if rtl.parameters has multiple items, the property generic gets set multiple time, resulting in generic having the value of the last item set.

With multiple items it generates this:
`set_property generic {PARAM_A=5} [current_fileset]`
`set_property generic {PARAM_B=3} [current_fileset]`
`set_property generic {PARAM_C=17} [current_fileset]`

The expected result is that "PARAM_A=5", "PARAM_B=3" and PARAM_C=10".
The actual result is that only "PARAM_C=10" is set.

Proposed fix:

`set_property generic "PARAM_A=5 PARAM_B=3 PARAM_C=17" [current_fileset]`

and the template code for that (not beautiful but works):

`set_property generic "
{%- for k,v in design.rtl.parameters.items() -%}
{% set x = ("1'b%d" % v) if v is boolean else v if v is not string else v if v is match("\\d+'b[01]+") else "\\\"" + v + "\\\"" -%}
 {{ k }}={{ x }}{{ " " }} 
{%- endfor -%}
" [current_fileset]
`

**Comment by kammoh** [comment]
Should be fixed in 0.1.0rc5. Please feel free to re-open if there were still any issues.
